# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-02 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
