# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-30 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
