# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-30 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiInfoTable',
            fields=[
                ('apiID', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('apiName', models.CharField(error_messages={b'required': b'\xe5\x90\x8d\xe7\xa7\xb0\xe4\xb8\x8d\xe8\x83\xbd\xe4\xb8\xba\xe7\xa9\xba'}, max_length=100)),
                ('lastRunResult', models.NullBooleanField()),
                ('lastRunTime', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=10)),
                ('url', models.URLField(blank=True)),
                ('headers', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('assertinfo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='countCase',
            fields=[
                ('pmID', models.IntegerField(primary_key=True, serialize=False)),
                ('allcaseNum', models.IntegerField()),
                ('passcaseNum', models.IntegerField()),
                ('failcaseNum', models.IntegerField()),
                ('blockvaseNum', models.IntegerField()),
                ('projectName', models.CharField(max_length=50, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
                ('moduleName', models.CharField(max_length=50, verbose_name=b'\xe6\xa8\xa1\xe5\x9d\x97\xe5\x90\x8d\xe7\xa7\xb0')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
        ),
        migrations.CreateModel(
            name='interfaceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe5\x90\x8d\xe7\xa7\xb0')),
                ('moduleName', models.CharField(max_length=50, verbose_name=b'\xe6\xa8\xa1\xe5\x9d\x97\xe5\x90\x8d\xe7\xa7\xb0')),
                ('host', models.CharField(max_length=50, verbose_name=b'\xe5\x9f\x9f\xe5\x90\x8d\xe5\x9c\xb0\xe5\x9d\x80')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe8\xbf\x91\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.AddField(
            model_name='apiinfotable',
            name='owningListID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.interfaceList'),
        ),
    ]
