# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_apiinfotable_countcase_interfacelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownMoudle', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('totalNum', models.IntegerField()),
                ('successNum', models.IntegerField()),
                ('failNum', models.IntegerField()),
                ('errorNum', models.IntegerField()),
                ('executor', models.CharField(max_length=50)),
                ('reportName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('depart_lever', models.IntegerField(default=3)),
                ('group', models.CharField(max_length=50, null=True)),
                ('batch_check', models.BooleanField(default=True)),
                ('batch_run', models.BooleanField(default=False)),
                ('batch_del', models.BooleanField(default=False)),
                ('configer_permit', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='apiinfotable',
            name='files',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apiinfotable',
            name='isRedirect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiinfotable',
            name='isScreat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiinfotable',
            name='key_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apiinfotable',
            name='secret_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
