# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190925_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_lever', models.IntegerField()),
                ('depart_name', models.CharField(max_length=50)),
            ],
        ),
    ]
